const http=require('http');const fs=require('fs');const path=require('path');
let Pool=null;
try{Pool=require('pg').Pool}catch{Pool=null}
const PORT=Number(process.env.PORT)||3000;const HOST='0.0.0.0';const ROOT=__dirname;const OPENAI_API_KEY=process.env.OPENAI_API_KEY||'';const OPENAI_MODEL=process.env.OPENAI_MODEL||'gpt-5.6-luna';
const pool=(Pool&&process.env.DATABASE_URL)?new Pool({connectionString:process.env.DATABASE_URL,ssl:{rejectUnauthorized:false},max:5,idleTimeoutMillis:30000}):null;
const MIME={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.svg':'image/svg+xml','.ico':'image/x-icon'};
function send(res,code,data,type='application/json; charset=utf-8'){if(res.headersSent)return;res.writeHead(code,{'Content-Type':type,'Cache-Control':'no-store'});res.end(Buffer.isBuffer(data)?data:typeof data==='string'?data:JSON.stringify(data))}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>15*1024*1024){reject(Error('PAYLOAD_TOO_LARGE'));req.destroy()}});req.on('end',()=>{if(!s)return resolve({});try{resolve(JSON.parse(s))}catch{reject(Error('JSON_INVALIDO'))}});req.on('error',reject)})}
async function db(sql,params=[]){if(!pool)throw Error('DATABASE_NAO_CONFIGURADO');return pool.query(sql,params)}
async function init(){if(!pool)return;await db(`CREATE TABLE IF NOT EXISTS tecidos(id BIGSERIAL PRIMARY KEY,payload JSONB NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE TABLE IF NOT EXISTS movimentos_tecido(id BIGSERIAL PRIMARY KEY,payload JSONB NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE TABLE IF NOT EXISTS romaneios(id BIGSERIAL PRIMARY KEY,draft_key TEXT,payload JSONB NOT NULL,status TEXT NOT NULL DEFAULT 'SALVO',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE UNIQUE INDEX IF NOT EXISTS romaneios_draft_key_idx ON romaneios(draft_key) WHERE status='RASCUNHO';`)}
function jsonExtract(r){if(typeof r?.output_text==='string')return r.output_text;return (r?.output||[]).flatMap(i=>(i?.content||[]).map(c=>c?.text||'')).join('\n')}
function parseJson(s){try{return JSON.parse(s)}catch{}const m=String(s||'').match(/\{[\s\S]*\}/);if(m)try{return JSON.parse(m[0])}catch{}return null}
async function ai(text){if(!OPENAI_API_KEY)throw Error('OPENAI_API_KEY_NAO_CONFIGURADA');const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),90000);try{const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${OPENAI_API_KEY}`},signal:controller.signal,body:JSON.stringify({model:OPENAI_MODEL,instructions:`VOCÊ É O LEITOR DE ROMANEIOS DE TECIDO DO ESTOQUE PLUS. RETORNE SOMENTE JSON VÁLIDO. NÃO INVENTE DADOS. DIFERENCIE ROMANEIO, NF, PEDIDO, TECIDO, ARTIGO, NUANCE, REFERÊNCIA, METROS, PEÇAS E PESOS. REGISTRE DIVERGÊNCIAS. CONFIANÇA DE 0 A 100. FORMATO: {\"documento\":{\"romaneio\":\"\",\"notaFiscal\":\"\",\"pedido\":\"\",\"data\":\"\"},\"produto\":{\"tecido\":\"\",\"artigo\":\"\",\"nuance\":\"\",\"referencia\":\"\"},\"totais\":{\"pecas\":null,\"metros\":null,\"pesoLiquido\":null,\"pesoBruto\":null},\"conferencia\":{\"divergencias\":[],\"observacoes\":[],\"confianca\":0}}`,input:text})});const t=await r.text();if(!r.ok)throw Error(`OPENAI_${r.status}: ${t.slice(0,700)}`);return parseJson(jsonExtract(JSON.parse(t)))||{conferencia:{confianca:0,divergencias:['A IA NÃO RETORNOU JSON VÁLIDO.'],observacoes:[jsonExtract(JSON.parse(t)).slice(0,1500)]}}}finally{clearTimeout(timer)}}
async function aiMiniRisk(imageData){if(!OPENAI_API_KEY)throw Error('OPENAI_API_KEY_NAO_CONFIGURADA');if(!/^data:image\/(png|jpe?g|webp);base64,/i.test(imageData))throw Error('IMAGEM_INVALIDA');const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),90000);try{const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${OPENAI_API_KEY}`},signal:controller.signal,body:JSON.stringify({model:OPENAI_MODEL,instructions:`LEIA A FOTO DE UM MINI RISCO DE CONFECÇÃO. RETORNE SOMENTE JSON VÁLIDO E NÃO INVENTE NÚMEROS. IDENTIFIQUE OC/TOTAL DE PEÇAS, GRADE POR TAMANHO E PARES. A GRADE É A SOMA DOS VALORES DOS TAMANHOS. SE A FOTO MOSTRAR UMA EXPRESSÃO COMO 16 X 130 = 2080, USE 16 COMO GRADE, 130 COMO PARES E 2080 COMO OC. TENTE OS TAMANHOS 36,38,40,42,44,46,48,50,52,54. FORMATO: {\"oc\":null,\"gradeTotal\":null,\"pares\":null,\"tamanhos\":{\"36\":0,\"38\":0,\"40\":0,\"42\":0,\"44\":0,\"46\":0,\"48\":0,\"50\":0,\"52\":0,\"54\":0},\"confianca\":0,\"observacoes\":[]}`,input:[{role:'user',content:[{type:'input_text',text:'LEIA ESTA FOTO DO MINI RISCO E EXTRAIA OS DADOS.'},{type:'input_image',image_url:imageData}]}]})});const t=await r.text();if(!r.ok)throw Error(`OPENAI_${r.status}: ${t.slice(0,700)}`);return parseJson(jsonExtract(JSON.parse(t)))||{confianca:0,observacoes:['A IA NÃO RETORNOU JSON VÁLIDO.']}}finally{clearTimeout(timer)}}
async function routes(req,res){const p=decodeURIComponent((req.url||'/').split('?')[0]);if(req.method==='GET'&&p==='/api/health')return send(res,200,{ok:true,service:'ESTOQUE DE TECIDO PLUS+ V26',database:Boolean(pool),aiConfigured:Boolean(OPENAI_API_KEY),model:OPENAI_MODEL});
if(req.method==='POST'&&p==='/api/ai'){const b=await body(req);if(b.mode==='romaneio_texto')return send(res,200,{ok:true,result:await ai(String(b.text||'').slice(0,50000))});if(b.mode==='mini_risco_imagem')return send(res,200,{ok:true,result:await aiMiniRisk(String(b.image||''))});return send(res,400,{ok:false,error:'MODO_DE_IA_NAO_SUPORTADO'})}
if(req.method==='GET'&&p==='/api/tecidos'){if(!pool)return send(res,200,{fabrics:[]});const q=await db('SELECT id,payload FROM tecidos ORDER BY id DESC');return send(res,200,{fabrics:q.rows.map(x=>({...x.payload,id:String(x.id)}))})}
if(req.method==='POST'&&p==='/api/tecidos'){const b=await body(req);if(!b.fabric||!Array.isArray(b.rolls)||!b.rolls.length)return send(res,400,{ok:false,error:'TECIDO_E_ROLOS_OBRIGATORIOS'});const payload={fabric:String(b.fabric).trim().toUpperCase(),nf:String(b.nf||'').trim().toUpperCase(),date:b.date||new Date().toISOString().slice(0,10),ref:String(b.ref||'').trim().toUpperCase(),rolls:b.rolls.map(r=>({id:String(r.id||Date.now()+Math.random()),nuance:String(r.nuance||'').trim().toUpperCase(),lot:String(r.lot||'').trim().toUpperCase(),meters:Number(r.meters),code:String(r.code||'').trim().toUpperCase()}))};if(!pool)return send(res,200,{fabric:{...payload,id:String(Date.now())}});const q=await db('INSERT INTO tecidos(payload) VALUES($1) RETURNING id,payload',[payload]);return send(res,200,{fabric:{...q.rows[0].payload,id:String(q.rows[0].id)}})}
if(req.method==='POST'&&p==='/api/tecidos/saida'){const b=await body(req);if(!pool){const m=Number(b.meters),pieces=Number(b.pieces);if(!String(b.rollId||''))return send(res,400,{ok:false,error:'ROLO_NAO_ENCONTRADO'});if(!Number.isFinite(m)||m<=0)return send(res,400,{ok:false,error:'METRAGEM_INVALIDA'});if(!Number.isInteger(pieces)||pieces<=0)return send(res,400,{ok:false,error:'PECAS_INVALIDAS'});return send(res,200,{localOnly:true,rollId:String(b.rollId),meters:m,pieces,oc:String(b.oc||'').trim().toUpperCase(),note:String(b.note||'').trim().toUpperCase()});}const all=await db('SELECT id,payload FROM tecidos');let owner=null;for(const row of all.rows){if((row.payload.rolls||[]).some(r=>String(r.id)===String(b.rollId))){owner=row;break}}if(!owner)return send(res,404,{ok:false,error:'ROLO_NAO_ENCONTRADO'});const roll=owner.payload.rolls.find(r=>String(r.id)===String(b.rollId));const m=Number(b.meters);if(!Number.isFinite(m)||m<=0)return send(res,400,{ok:false,error:'METRAGEM_INVALIDA'});if(m>Number(roll.meters)+1e-9)return send(res,400,{ok:false,error:'METRAGEM_MAIOR_QUE_DISPONIVEL'});roll.meters=Number((Number(roll.meters)-m).toFixed(3));const payload={type:'SAÍDA',date:new Date().toISOString().slice(0,10),fabric:owner.payload.fabric,nuance:roll.nuance||'',meters:m,pieces:Number(b.pieces),oc:String(b.oc||'').trim().toUpperCase(),note:String(b.note||'').trim().toUpperCase(),rollId:String(b.rollId)};const nq=await db('UPDATE tecidos SET payload=$1,updated_at=NOW() WHERE id=$2 RETURNING id,payload',[owner.payload,String(owner.id)]);await db('INSERT INTO movimentos_tecido(payload) VALUES($1)',[payload]);return send(res,200,{fabric:{...nq.rows[0].payload,id:String(nq.rows[0].id)}})}
if(req.method==='GET'&&p==='/api/movimentos'){if(!pool)return send(res,200,{history:[]});const q=await db('SELECT id,payload,created_at FROM movimentos_tecido ORDER BY id DESC LIMIT 500');return send(res,200,{history:q.rows.map(x=>({...x.payload,id:String(x.id),created_at:x.created_at}))})}
if(req.method==='POST'&&p==='/api/romaneios/draft'){const b=await body(req);if(!pool)return send(res,200,{ok:true,localOnly:true});const key=String(b.draftKey||'tecnoflow');const payload=b.payload||{};const q=await db(`INSERT INTO romaneios(draft_key,payload,status) VALUES($1,$2,'RASCUNHO') ON CONFLICT(draft_key) WHERE status='RASCUNHO' DO UPDATE SET payload=EXCLUDED.payload,updated_at=NOW() RETURNING id,payload,status,updated_at`,[key,payload]);return send(res,200,{ok:true,romaneio:{...q.rows[0],id:String(q.rows[0].id)}})}
if(req.method==='POST'&&p==='/api/romaneios'){const b=await body(req);const payload=b.payload||{};if(!payload.text)return send(res,400,{ok:false,error:'ROMANEIO_VAZIO'});if(!pool)return send(res,200,{ok:true,romaneio:{id:String(Date.now()),payload,status:'SALVO',created_at:new Date().toISOString()}});const key=String(b.draftKey||'');const q=key?await db(`UPDATE romaneios SET payload=$1,status='SALVO',updated_at=NOW() WHERE draft_key=$2 AND status='RASCUNHO' RETURNING id,payload,status,created_at`,[payload,key]):{rows:[]};if(q.rows.length)return send(res,200,{ok:true,romaneio:{...q.rows[0],id:String(q.rows[0].id)}});const n=await db(`INSERT INTO romaneios(payload,status) VALUES($1,'SALVO') RETURNING id,payload,status,created_at`,[payload]);return send(res,200,{ok:true,romaneio:{...n.rows[0],id:String(n.rows[0].id)}})}
if(req.method==='GET'&&p==='/api/romaneios'){if(!pool)return send(res,200,{romaneios:[]});const q=await db(`SELECT id,payload,status,created_at FROM romaneios WHERE status='SALVO' ORDER BY id DESC LIMIT 200`);return send(res,200,{romaneios:q.rows.map(x=>({...x,id:String(x.id)}))})}
if(req.method==='GET'){const rel=path.normalize(p==='/'?'/index.html':p).replace(/^[/\\]+/,'');const roots=[path.resolve(ROOT,'public'),ROOT];for(const base of roots){const file=path.resolve(base,rel);if(file!==base&&!file.startsWith(base+path.sep))continue;if(fs.existsSync(file)&&fs.statSync(file).isFile()){const ext=path.extname(file).toLowerCase();if(file===path.resolve(ROOT,'server.js')||file===path.resolve(ROOT,'package.json'))continue;return send(res,200,fs.readFileSync(file),MIME[ext]||'application/octet-stream')}}}
return send(res,404,{ok:false,error:'NOT_FOUND'})}
const server=http.createServer((req,res)=>routes(req,res).catch(e=>{console.error(e);send(res,500,{ok:false,error:e.message||'ERRO_INTERNO'})}));
init().then(()=>server.listen(PORT,HOST,()=>console.log(`ESTOQUE DE TECIDO PLUS+ V26 ON ${PORT}`))).catch(e=>{console.error('DB INIT',e);server.listen(PORT,HOST,()=>console.log(`ESTOQUE DE TECIDO PLUS+ V26 ON ${PORT} SEM DB`))});
process.on('SIGTERM',async()=>{server.close();if(pool)await pool.end();process.exit(0)});
