const http=require('http');const fs=require('fs');const path=require('path');const crypto=require('crypto');
let Pool=null;
try{Pool=require('pg').Pool}catch{Pool=null}
const PORT=Number(process.env.PORT)||3000;const HOST='0.0.0.0';const ROOT=__dirname;const OPENAI_API_KEY=process.env.OPENAI_API_KEY||'';const OPENAI_MODEL=process.env.OPENAI_MODEL||'gpt-5.6-sol';
const APP_VERSION='V35 MULTIEMPRESA + OWNER + OFICINAS + HISTÓRICO';
const INITIAL_ADMIN_USER='admin';
const INITIAL_ADMIN_PASSWORD='admin123';
const SESSION_TTL_MS=8*60*60*1000;
const LOGIN_WINDOW_MS=15*60*1000;
const LOGIN_MAX_ATTEMPTS=8;
const loginAttempts=new Map();
const sessions=new Map();
function parseCookies(req){const out={};for(const part of String(req.headers.cookie||'').split(';')){const i=part.indexOf('=');if(i>0)out[part.slice(0,i).trim()]=decodeURIComponent(part.slice(i+1).trim())}return out}
function authUser(req){const token=parseCookies(req).estoque_session;if(!token)return null;const s=sessions.get(token);if(!s)return null;if(Date.now()>s.expires){sessions.delete(token);return null}s.expires=Date.now()+SESSION_TTL_MS;return s.user}
function hashPassword(password){const salt=crypto.randomBytes(16);const hash=crypto.scryptSync(String(password),salt,64,{N:16384,r:8,p:1});return `scrypt$${salt.toString('hex')}$${hash.toString('hex')}`}
function verifyPassword(password,stored){try{const [alg,saltHex,hashHex]=String(stored||'').split('$');if(alg!=='scrypt'||!saltHex||!hashHex)return false;const salt=Buffer.from(saltHex,'hex'),expected=Buffer.from(hashHex,'hex');const actual=crypto.scryptSync(String(password),salt,expected.length,{N:16384,r:8,p:1});return actual.length===expected.length&&crypto.timingSafeEqual(actual,expected)}catch{return false}}
function cleanUsername(v){return String(v||'').trim().toLowerCase().replace(/[^a-z0-9_.-]/g,'').slice(0,40)}
async function currentDbUser(req){const u=authUser(req);if(!u)return null;if(!pool)return typeof u==='object'?u:{username:String(u),role:'ADMIN'};try{const q=await db('SELECT id,username,role,active,company_id FROM app_users WHERE username=$1',[typeof u==='object'?u.username:String(u)]);return q.rows[0]||null}catch{return null}}
async function currentSession(req){const u=authUser(req);return u&&typeof u==='object'?u:null}
async function requireOwner(req,res){const u=await currentDbUser(req);if(!u||u.active===false||String(u.role).toUpperCase()!=='OWNER'){send(res,403,{ok:false,error:'ACESSO_OWNER_NECESSARIO'});return null}return u}
async function scopeCompanyId(req){const u=await currentDbUser(req);if(!u)return null;if(String(u.role).toUpperCase()==='OWNER'){const s=await currentSession(req);return s?.activeCompanyId?Number(s.activeCompanyId):null}return u.company_id?Number(u.company_id):null}
async function requireScope(req,res){const companyId=await scopeCompanyId(req);if(!companyId){send(res,400,{ok:false,error:'EMPRESA_NAO_SELECIONADA'});return null}return companyId}
async function requireAdmin(req,res){const u=await currentDbUser(req);if(!u||u.active===false||!['ADMIN','OWNER'].includes(String(u.role).toUpperCase())){send(res,403,{ok:false,error:'ACESSO_ADMIN_NECESSARIO'});return null}return u}
function clientKey(req){return String(req.headers['x-forwarded-for']||req.socket.remoteAddress||'unknown').split(',')[0].trim()}
function loginAllowed(req){const now=Date.now(),key=clientKey(req),a=loginAttempts.get(key);if(!a||now-a.started>LOGIN_WINDOW_MS){loginAttempts.set(key,{started:now,count:0});return true}return a.count<LOGIN_MAX_ATTEMPTS}
function recordLoginFailure(req){const now=Date.now(),key=clientKey(req),a=loginAttempts.get(key);if(!a||now-a.started>LOGIN_WINDOW_MS){loginAttempts.set(key,{started:now,count:1});return}a.count++}
function clearLoginFailures(req){loginAttempts.delete(clientKey(req))}
function cleanSessions(){const now=Date.now();for(const [k,v] of sessions)if(v.expires<now)sessions.delete(k);for(const [k,v] of loginAttempts)if(now-v.started>LOGIN_WINDOW_MS)loginAttempts.delete(k);if(sessions.size>5000){for(const [k,v] of sessions)if(v.expires<now)sessions.delete(k)}}
const AI_RATE_LIMIT=20;const AI_RATE_WINDOW_MS=60_000;const aiRate=new Map();
const pool=(Pool&&process.env.DATABASE_URL)?new Pool({connectionString:process.env.DATABASE_URL,ssl:{rejectUnauthorized:false},max:5,idleTimeoutMillis:30000}):null;
const MIME={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.svg':'image/svg+xml','.ico':'image/x-icon'};
function send(res,code,data,type='application/json; charset=utf-8'){if(res.headersSent)return;res.writeHead(code,{'Content-Type':type,'Cache-Control':'no-store'});res.end(Buffer.isBuffer(data)?data:typeof data==='string'?data:JSON.stringify(data))}
function body(req){return new Promise((resolve,reject)=>{let s='',tooLarge=false;req.on('data',c=>{if(tooLarge)return;s+=c;if(s.length>15*1024*1024){tooLarge=true;reject(Object.assign(Error('PAYLOAD_TOO_LARGE'),{statusCode:413}));req.resume()}});req.on('end',()=>{if(tooLarge)return;if(!s)return resolve({});try{resolve(JSON.parse(s))}catch{reject(Object.assign(Error('JSON_INVALIDO'),{statusCode:400}))}});req.on('error',reject)})}
async function db(sql,params=[]){if(!pool)throw Error('DATABASE_NAO_CONFIGURADO');return pool.query(sql,params)}
async function init(){
 if(!pool)return;
 await db(`CREATE TABLE IF NOT EXISTS companies(id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL,cnpj TEXT,contact_name TEXT,contact_email TEXT,phone TEXT,plan TEXT NOT NULL DEFAULT 'TRIAL',status TEXT NOT NULL DEFAULT 'ATIVA',trial_ends_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS tecidos(id BIGSERIAL PRIMARY KEY,payload JSONB NOT NULL,company_id BIGINT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS movimentos_tecido(id BIGSERIAL PRIMARY KEY,payload JSONB NOT NULL,company_id BIGINT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS romaneios(id BIGSERIAL PRIMARY KEY,draft_key TEXT,payload JSONB NOT NULL,status TEXT NOT NULL DEFAULT 'SALVO',company_id BIGINT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS aviamentos(id TEXT NOT NULL,payload JSONB NOT NULL,company_id BIGINT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),version BIGINT NOT NULL DEFAULT 1);
 CREATE TABLE IF NOT EXISTS oficinas(id BIGSERIAL PRIMARY KEY,company_id BIGINT NOT NULL,name TEXT NOT NULL,code TEXT,contact_name TEXT,phone TEXT,address TEXT,active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS envios_aviamentos(id BIGSERIAL PRIMARY KEY,company_id BIGINT NOT NULL,oficina_id BIGINT NOT NULL,user_id BIGINT,oc TEXT,notes TEXT,items JSONB NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS app_users(id BIGSERIAL PRIMARY KEY,username TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'OPERADOR',active BOOLEAN NOT NULL DEFAULT TRUE,company_id BIGINT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 DROP INDEX IF EXISTS romaneios_draft_key_idx;CREATE UNIQUE INDEX IF NOT EXISTS romaneios_draft_key_idx ON romaneios(company_id,draft_key) WHERE status='RASCUNHO';
 CREATE INDEX IF NOT EXISTS movimentos_tecido_created_idx ON movimentos_tecido(company_id,created_at DESC);CREATE INDEX IF NOT EXISTS tecidos_updated_idx ON tecidos(company_id,updated_at DESC);CREATE INDEX IF NOT EXISTS aviamentos_company_idx ON aviamentos(company_id,id);CREATE UNIQUE INDEX IF NOT EXISTS aviamentos_company_id_idx ON aviamentos(company_id,id);CREATE INDEX IF NOT EXISTS oficinas_company_idx ON oficinas(company_id,active);CREATE INDEX IF NOT EXISTS envios_aviamentos_company_idx ON envios_aviamentos(company_id,created_at DESC);`);
 const c=await db('SELECT id FROM companies ORDER BY id LIMIT 1');
 let defaultCompanyId=c.rows[0]?.id;
 if(!defaultCompanyId){const n=await db(`INSERT INTO companies(name,plan,status) VALUES($1,'TRIAL','ATIVA') RETURNING id`,['RED WAY - EMPRESA PRINCIPAL']);defaultCompanyId=n.rows[0].id;}
 await db(`ALTER TABLE tecidos ADD COLUMN IF NOT EXISTS company_id BIGINT;ALTER TABLE movimentos_tecido ADD COLUMN IF NOT EXISTS company_id BIGINT;ALTER TABLE romaneios ADD COLUMN IF NOT EXISTS company_id BIGINT;ALTER TABLE aviamentos ADD COLUMN IF NOT EXISTS company_id BIGINT;ALTER TABLE app_users ADD COLUMN IF NOT EXISTS company_id BIGINT;`);
 await db(`UPDATE tecidos SET company_id=$1 WHERE company_id IS NULL;UPDATE movimentos_tecido SET company_id=$1 WHERE company_id IS NULL;UPDATE romaneios SET company_id=$1 WHERE company_id IS NULL;UPDATE aviamentos SET company_id=$1 WHERE company_id IS NULL;`,[defaultCompanyId]);
 await db(`ALTER TABLE aviamentos DROP CONSTRAINT IF EXISTS aviamentos_pkey;ALTER TABLE aviamentos ALTER COLUMN company_id SET NOT NULL;ALTER TABLE aviamentos ALTER COLUMN id SET NOT NULL;CREATE UNIQUE INDEX IF NOT EXISTS aviamentos_company_id_unique ON aviamentos(company_id,id);`);
 await db(`UPDATE app_users SET role='OWNER',company_id=NULL WHERE role='ADMIN' AND id=(SELECT id FROM app_users ORDER BY id LIMIT 1);UPDATE app_users SET company_id=$1 WHERE company_id IS NULL AND role<>'OWNER';`,[defaultCompanyId]);
 const n=await db('SELECT COUNT(*)::int AS n FROM app_users');
 if(Number(n.rows[0].n)===0){const u=INITIAL_ADMIN_USER;const pass=INITIAL_ADMIN_PASSWORD;await db('INSERT INTO app_users(username,password_hash,role,company_id) VALUES($1,$2,$3,NULL)',[u,hashPassword(pass),'OWNER']);console.log(`OWNER INICIAL CRIADO PARA ${u}. ALTERE A SENHA DENTRO DO SISTEMA.`)}
}
function jsonExtract(r){if(typeof r?.output_text==='string')return r.output_text;return (r?.output||[]).flatMap(i=>(i?.content||[]).map(c=>c?.text||'')).join('\n')}
function parseJson(s){try{return JSON.parse(s)}catch{}const m=String(s||'').match(/\{[\s\S]*\}/);if(m)try{return JSON.parse(m[0])}catch{}return null}
async function ai(text){if(!OPENAI_API_KEY)throw Error('OPENAI_API_KEY_NAO_CONFIGURADA');const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),90000);try{const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${OPENAI_API_KEY}`},signal:controller.signal,body:JSON.stringify({model:OPENAI_MODEL,instructions:`VOCÊ É O LEITOR DE ROMANEIOS DE TECIDO DO ESTOQUE PLUS. RETORNE SOMENTE JSON VÁLIDO. NÃO INVENTE DADOS. DIFERENCIE ROMANEIO, NF, PEDIDO, TECIDO, ARTIGO, NUANCE, REFERÊNCIA, METROS, PEÇAS E PESOS. REGISTRE DIVERGÊNCIAS. CONFIANÇA DE 0 A 100. FORMATO: {\"documento\":{\"romaneio\":\"\",\"notaFiscal\":\"\",\"pedido\":\"\",\"data\":\"\"},\"produto\":{\"tecido\":\"\",\"artigo\":\"\",\"nuance\":\"\",\"referencia\":\"\"},\"totais\":{\"pecas\":null,\"metros\":null,\"pesoLiquido\":null,\"pesoBruto\":null},\"conferencia\":{\"divergencias\":[],\"observacoes\":[],\"confianca\":0}}`,input:text})});const t=await r.text();if(!r.ok)throw Error(`OPENAI_${r.status}: ${t.slice(0,700)}`);return parseJson(jsonExtract(JSON.parse(t)))||{conferencia:{confianca:0,divergencias:['A IA NÃO RETORNOU JSON VÁLIDO.'],observacoes:[jsonExtract(JSON.parse(t)).slice(0,1500)]}}}finally{clearTimeout(timer)}}
async function callOpenAI(instructions,input,timeout=90000){if(!OPENAI_API_KEY)throw Error('OPENAI_API_KEY_NAO_CONFIGURADA');const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeout);try{const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${OPENAI_API_KEY}`},signal:controller.signal,body:JSON.stringify({model:OPENAI_MODEL,instructions,input})});const t=await r.text();if(!r.ok)throw Error(`OPENAI_${r.status}: ${t.slice(0,700)}`);return JSON.parse(t)}finally{clearTimeout(timer)}}
function safeContext(context){const c=context&&typeof context==='object'?context:{};return JSON.stringify(c).slice(0,70000)}
async function aiAssistant(message,context={},history=[]){const system=`VOCÊ É A IA CENTRAL DO ESTOQUE DE TECIDO PLUS+, UM ASSISTENTE OPERACIONAL DE ALTO NÍVEL.
MISSÃO: ajudar a controlar tecidos e aviamentos, conferir cortes e romaneios, fazer cálculos exatos, detectar inconsistências, explicar causas e montar planos de ação.
CAPACIDADES: análise de estoque, cálculo de necessidade, conferência OC/grade/pares, análise de rolos/nuances, leitura e auditoria de romaneios, comparação de dados, detecção de divergências, planejamento de reposição e perguntas de esclarecimento.
REGRAS DE CONFIABILIDADE: NUNCA INVENTE estoque, histórico, medidas ou movimentações. Diferencie claramente DADO INFORMADO, CÁLCULO, INFERÊNCIA e ALERTA. Se faltar dado, peça somente o dado necessário. Refaça contas antes de responder.
REGRAS DE AVIAMENTOS: CÓS 1,3 M/PEÇA, ROLO 50 M; REFLETIVO 1,0 M/PEÇA, ROLO 50 M, 20 ROLOS/CAIXA; ELÁSTICO 0,8 M/PEÇA, ROLO 25 M; ZÍPER 1/PEÇA, pacote padrão 100; ETIQUETA TAMANHO 0,35 G/PEÇA; ETIQUETA COMPOSIÇÃO 0,4 G/PEÇA. GRADE PADRÃO: 38,40,42,44,46,48.
ESTOQUE: quando houver estoque disponível no contexto, compare necessidade com estoque e mostre saldo projetado. Não baixe estoque nem altere dados sem uma ação explícita do usuário.
FORMATO: português do Brasil, direto, organizado, números em padrão brasileiro. Para problemas, use: RESUMO / DADOS / CÁLCULO / ALERTAS / PRÓXIMA AÇÃO.
CONTEXTO ATUAL: ${safeContext(context)}
HISTÓRICO RECENTE DA CONVERSA: ${JSON.stringify(Array.isArray(history)?history.slice(-12):[]).slice(0,20000)}`;const r=await callOpenAI(system,String(message||'').slice(0,20000));const out=jsonExtract(r);return {answer:out||'NÃO FOI POSSÍVEL GERAR UMA RESPOSTA.'}}
async function aiInsights(context={}){const system=`VOCÊ É O AUDITOR INTELIGENTE DO ESTOQUE DE TECIDO PLUS+.
Analise os dados fornecidos e produza uma auditoria operacional. Não invente nada. Só trate como alerta aquilo que puder ser sustentado pelos dados. Para estoque de aviamentos, compare estoque atual com necessidades calculadas quando existirem. Para tecidos, procure rolos com metragem inválida, dados incompletos, possíveis duplicidades e concentrações por nuance. Para romaneios, procure campos vazios, valores incompatíveis e divergências já registradas.
RETORNE SOMENTE JSON válido no formato: {"resumo":"","nivel":"NORMAL|ATENCAO|CRITICO","alertas":[{"item":"","tipo":"","detalhe":""}],"prioridades":[""],"recomendacoes":[""],"dados_faltantes":[""],"confianca":0}. Não faça baixa nem alteração de estoque. CONTEXTO: ${safeContext(context)}`;const r=await callOpenAI(system,'FAÇA A AUDITORIA COMPLETA DOS DADOS ATUAIS.');return parseJson(jsonExtract(r))||{resumo:'A IA não retornou JSON válido.',nivel:'ATENCAO',alertas:[],prioridades:[],recomendacoes:[],dados_faltantes:[],confianca:0}}
async function aiMiniRisk(imageData){if(!OPENAI_API_KEY)throw Error('OPENAI_API_KEY_NAO_CONFIGURADA');if(!/^data:image\/(png|jpe?g|webp);base64,/i.test(imageData))throw Error('IMAGEM_INVALIDA');const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),90000);try{const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${OPENAI_API_KEY}`},signal:controller.signal,body:JSON.stringify({model:OPENAI_MODEL,instructions:`LEIA A FOTO DE UM MINI RISCO DE CONFECÇÃO. RETORNE SOMENTE JSON VÁLIDO E NÃO INVENTE NÚMEROS. IDENTIFIQUE OC/TOTAL DE PEÇAS, GRADE POR TAMANHO, PARES E TAMBÉM CONTE AS PARTES VISÍVEIS DO RISCO. “PARTES” SÃO COMPONENTES DO CORTE, NÃO AVIAMENTOS DE PRODUÇÃO. PROCURE NOMES COMO FRENTE, TRASEIRA, PERNA, BOLSO, PALA, REVEL, PASSANTE, VISTA LARGA, VISTA ESTREITA E BOLSO RELÓGIO. CONTE APENAS O QUE CONSEGUIR LER/IDENTIFICAR NA FOTO; QUANDO NÃO FOR POSSÍVEL, USE null E REGISTRE A DÚVIDA. A GRADE É A SOMA DOS VALORES DOS TAMANHOS. SE A FOTO MOSTRAR UMA EXPRESSÃO COMO 16 X 130 = 2080, USE 16 COMO GRADE, 130 COMO PARES E 2080 COMO OC. TENTE OS TAMANHOS 36,38,40,42,44,46,48,50,52,54. FORMATO: {"oc":null,"gradeTotal":null,"pares":null,"tamanhos":{"36":0,"38":0,"40":0,"42":0,"44":0,"46":0,"48":0,"50":0,"52":0,"54":0},"partes":{"frente":null,"traseira":null,"perna":null,"bolso":null,"pala":null,"revel":null,"passante":null,"vista_larga":null,"vista_estreita":null,"bolso_relogio":null},"confianca":0,"observacoes":[]}`,input:[{role:'user',content:[{type:'input_text',text:'LEIA ESTA FOTO DO MINI RISCO E EXTRAIA OS DADOS.'},{type:'input_image',image_url:imageData}]}]})});const t=await r.text();if(!r.ok)throw Error(`OPENAI_${r.status}: ${t.slice(0,700)}`);return parseJson(jsonExtract(JSON.parse(t)))||{confianca:0,observacoes:['A IA NÃO RETORNOU JSON VÁLIDO.']}}finally{clearTimeout(timer)}}
function allowAI(req){const now=Date.now();const ip=String(req.headers['x-forwarded-for']||req.socket.remoteAddress||'unknown').split(',')[0].trim();const hit=aiRate.get(ip)||{at:now,count:0};if(now-hit.at>=AI_RATE_WINDOW_MS){hit.at=now;hit.count=0}hit.count++;aiRate.set(ip,hit);if(aiRate.size>5000){for(const [k,v] of aiRate)if(now-v.at>AI_RATE_WINDOW_MS)aiRate.delete(k)}return hit.count<=AI_RATE_LIMIT}
async function routes(req,res){const p=decodeURIComponent((req.url||'/').split('?')[0]);cleanSessions();if(req.method==='GET'&&p==='/api/health'){let dbOk=false,dbLatency=null;if(pool){const t=Date.now();try{await db('SELECT 1');dbOk=true;dbLatency=Date.now()-t}catch{}}return send(res,200,{ok:true,service:`ESTOQUE DE TECIDO PLUS+ ${APP_VERSION}`,version:APP_VERSION,database:dbOk,loginConfigured:Boolean(pool),aiConfigured:Boolean(OPENAI_API_KEY),model:OPENAI_MODEL,dbLatencyMs:dbLatency,serverTime:new Date().toISOString(),multiTenant:true,ownerModel:true,officeHistory:true})}
if(req.method==='GET'&&p==='/api/auth/status'){return send(res,200,{ok:true,configured:Boolean(pool),userConfigured:Boolean(pool)})}
if(req.method==='POST'&&p==='/api/auth/login'){const b=await body(req);if(!pool)return send(res,503,{ok:false,error:'BANCO_DE_USUARIOS_NAO_CONFIGURADO'});if(!loginAllowed(req))return send(res,429,{ok:false,error:'MUITAS_TENTATIVAS_LOGIN','retryAfterSeconds':Math.max(1,Math.ceil((LOGIN_WINDOW_MS-(Date.now()-(loginAttempts.get(clientKey(req))?.started||Date.now())))/1000))});const username=cleanUsername(b.user);const q=await db('SELECT id,username,password_hash,role,active,company_id FROM app_users WHERE username=$1',[username]);const row=q.rows[0];const passOk=Boolean(row&&row.active&&verifyPassword(b.password,row.password_hash));if(!row||!passOk){recordLoginFailure(req);return send(res,401,{ok:false,error:'USUARIO_OU_SENHA_INVALIDOS'})}clearLoginFailures(req);const token=crypto.randomBytes(32).toString('hex');let activeCompanyId=row.company_id?Number(row.company_id):null;if(String(row.role).toUpperCase()==='OWNER'&&!activeCompanyId){const cq=await db("SELECT id FROM companies WHERE status='ATIVA' ORDER BY id LIMIT 1");activeCompanyId=cq.rows[0]?.id||null}sessions.set(token,{user:{id:Number(row.id),username:row.username,role:row.role,companyId:row.company_id?Number(row.company_id):null},activeCompanyId,expires:Date.now()+SESSION_TTL_MS});const secure=String(process.env.RENDER||'').toLowerCase()==='true'||String(req.headers['x-forwarded-proto']||'').split(',')[0].trim()==='https';res.setHeader('Set-Cookie',`estoque_session=${encodeURIComponent(token)}; HttpOnly; Path=/; SameSite=Lax; ${secure?'Secure; ':''}Max-Age=${Math.floor(SESSION_TTL_MS/1000)}`);return send(res,200,{ok:true,user:{username:row.username,role:row.role,companyId:row.company_id?Number(row.company_id):null,activeCompanyId},expiresAt:new Date(Date.now()+SESSION_TTL_MS).toISOString()})}
if(req.method==='POST'&&p==='/api/auth/logout'){const token=parseCookies(req).estoque_session;if(token)sessions.delete(token);res.setHeader('Set-Cookie','estoque_session=; HttpOnly; Path=/; SameSite=Lax; Max-Age=0');return send(res,200,{ok:true})}
if(req.method==='GET'&&p==='/api/auth/me'){const user=await currentDbUser(req);const sess=await currentSession(req);return send(res,200,{authenticated:Boolean(user&&user.active!==false),user:user?{id:Number(user.id),username:user.username,role:user.role,companyId:user.company_id?Number(user.company_id):null,activeCompanyId:sess?.activeCompanyId||null}:null})}
if(req.method==='POST'&&p==='/api/auth/change-password'){const user=await currentDbUser(req);if(!user)return send(res,401,{ok:false,error:'LOGIN_OBRIGATORIO'});const b=await body(req);if(!b.currentPassword||String(b.newPassword||'').length<8)return send(res,400,{ok:false,error:'SENHA_NOVA_MINIMO_8_CARACTERES'});const q=await db('SELECT password_hash FROM app_users WHERE id=$1',[user.id]);if(!q.rows.length||!verifyPassword(b.currentPassword,q.rows[0].password_hash))return send(res,400,{ok:false,error:'SENHA_ATUAL_INCORRETA'});await db('UPDATE app_users SET password_hash=$1,updated_at=NOW() WHERE id=$2',[hashPassword(b.newPassword),user.id]);return send(res,200,{ok:true})}
if(req.method==='GET'&&p==='/api/companies'){const owner=await requireOwner(req,res);if(!owner)return;const q=await db(`SELECT id,name,cnpj,contact_name,contact_email,phone,plan,status,trial_ends_at,created_at FROM companies ORDER BY id DESC`);return send(res,200,{companies:q.rows})}
if(req.method==='POST'&&p==='/api/companies'){const owner=await requireOwner(req,res);if(!owner)return;const b=await body(req);const name=String(b.name||'').trim().toUpperCase();if(name.length<2)return send(res,400,{ok:false,error:'NOME_DA_EMPRESA_OBRIGATORIO'});const q=await db(`INSERT INTO companies(name,cnpj,contact_name,contact_email,phone,plan,status,trial_ends_at) VALUES($1,$2,$3,$4,$5,$6,'ATIVA',$7) RETURNING *`,[name,String(b.cnpj||'').trim(),String(b.contactName||'').trim(),String(b.email||'').trim().toLowerCase(),String(b.phone||'').trim(),String(b.plan||'TRIAL').toUpperCase(),b.trialEndsAt||null]);return send(res,200,{ok:true,company:q.rows[0]})}
if(req.method==='POST'&&p.startsWith('/api/companies/')&&p.endsWith('/select')){const owner=await requireOwner(req,res);if(!owner)return;const id=Number(p.slice('/api/companies/'.length,-'/select'.length));const q=await db('SELECT id,name,status FROM companies WHERE id=$1',[id]);if(!q.rows.length)return send(res,404,{ok:false,error:'EMPRESA_NAO_ENCONTRADA'});const token=parseCookies(req).estoque_session;const sess=sessions.get(token);if(sess){sess.activeCompanyId=id;sess.expires=Date.now()+SESSION_TTL_MS}return send(res,200,{ok:true,company:q.rows[0]})}
if(req.method==='GET'&&p==='/api/context'){const user=await currentDbUser(req);if(!user)return send(res,401,{ok:false,error:'LOGIN_OBRIGATORIO'});const sess=await currentSession(req);let company=null;if(sess?.activeCompanyId){const q=await db('SELECT id,name,cnpj,plan,status FROM companies WHERE id=$1',[sess.activeCompanyId]);company=q.rows[0]||null}else if(user.company_id){const q=await db('SELECT id,name,cnpj,plan,status FROM companies WHERE id=$1',[user.company_id]);company=q.rows[0]||null}return send(res,200,{ok:true,user:{id:Number(user.id),username:user.username,role:user.role},company})}
if(req.method==='GET'&&p==='/api/users'){const admin=await requireAdmin(req,res);if(!admin)return;const companyId=await scopeCompanyId(req);const q=String(admin.role).toUpperCase()==='OWNER'&&!companyId?await db('SELECT id,username,role,active,company_id,created_at,updated_at FROM app_users ORDER BY username'):await db('SELECT id,username,role,active,company_id,created_at,updated_at FROM app_users WHERE company_id=$1 ORDER BY username',[companyId]);return send(res,200,{users:q.rows})}
if(req.method==='POST'&&p==='/api/users'){const admin=await requireAdmin(req,res);if(!admin)return;const b=await body(req);const username=cleanUsername(b.username);const password=String(b.password||'');const requestedRole=String(b.role||'OPERADOR').toUpperCase();const role=['OWNER','ADMIN','OPERADOR'].includes(requestedRole)?requestedRole:'OPERADOR';if(String(admin.role).toUpperCase()!=='OWNER'&&role==='OWNER')return send(res,403,{ok:false,error:'SOMENTE_OWNER_PODE_CRIAR_OWNER'});const companyId=role==='OWNER'?null:(String(admin.role).toUpperCase()==='OWNER'&&b.companyId?Number(b.companyId):await scopeCompanyId(req));if(role!=='OWNER'&&!companyId)return send(res,400,{ok:false,error:'EMPRESA_OBRIGATORIA'});if(!username||username.length<3||password.length<8)return send(res,400,{ok:false,error:'USUARIO_MINIMO_3_E_SENHA_MINIMO_8'});try{const q=await db('INSERT INTO app_users(username,password_hash,role,active,company_id) VALUES($1,$2,$3,TRUE,$4) RETURNING id,username,role,active,company_id',[username,hashPassword(password),role,companyId]);return send(res,200,{ok:true,user:q.rows[0]})}catch(e){if(String(e.code)==='23505')return send(res,409,{ok:false,error:'USUARIO_JA_EXISTE'});throw e}}
if((req.method==='PATCH'||req.method==='POST')&&p.startsWith('/api/users/')&&p.endsWith('/status')){const admin=await requireAdmin(req,res);if(!admin)return;const id=Number(p.slice('/api/users/'.length,-'/status'.length));const b=await body(req);if(id===Number(admin.id)&&b.active===false)return send(res,400,{ok:false,error:'NAO_DESATIVE_SEU_PROPRIO_USUARIO'});const companyId=await scopeCompanyId(req);const where=String(admin.role).toUpperCase()==='OWNER'?'id=$1':'id=$1 AND company_id=$2';const params=String(admin.role).toUpperCase()==='OWNER'?[id]:[id,companyId];const q=String(admin.role).toUpperCase()==='OWNER'?await db('UPDATE app_users SET active=$1,updated_at=NOW() WHERE id=$2 RETURNING id,username,role,active,company_id',[Boolean(b.active),id]):await db('UPDATE app_users SET active=$1,updated_at=NOW() WHERE id=$2 AND company_id=$3 RETURNING id,username,role,active,company_id',[Boolean(b.active),id,companyId]);if(!q.rows.length)return send(res,404,{ok:false,error:'USUARIO_NAO_ENCONTRADO'});return send(res,200,{ok:true,user:q.rows[0]})}
if((req.method==='PATCH'||req.method==='POST')&&p.startsWith('/api/users/')&&p.endsWith('/password')){const admin=await requireAdmin(req,res);if(!admin)return;const id=Number(p.slice('/api/users/'.length,-'/password'.length));const b=await body(req);if(String(b.password||'').length<8)return send(res,400,{ok:false,error:'SENHA_MINIMO_8_CARACTERES'});const companyId=await scopeCompanyId(req);const q=String(admin.role).toUpperCase()==='OWNER'?await db('UPDATE app_users SET password_hash=$1,updated_at=NOW() WHERE id=$2 RETURNING id,username,role,active,company_id',[hashPassword(b.password),id]):await db('UPDATE app_users SET password_hash=$1,updated_at=NOW() WHERE id=$2 AND company_id=$3 RETURNING id,username,role,active,company_id',[hashPassword(b.password),id,companyId]);if(!q.rows.length)return send(res,404,{ok:false,error:'USUARIO_NAO_ENCONTRADO'});return send(res,200,{ok:true,user:q.rows[0]})}
if(p.startsWith('/api/')&&!['/api/health','/api/auth/status','/api/auth/login','/api/auth/logout','/api/auth/me'].includes(p)){if(!authUser(req))return send(res,401,{ok:false,error:'LOGIN_OBRIGATORIO'})}
if(req.method==='POST'&&p==='/api/ai'){if(!OPENAI_API_KEY)return send(res,503,{ok:false,error:'OPENAI_API_KEY_NAO_CONFIGURADA'});if(!allowAI(req))return send(res,429,{ok:false,error:'LIMITE_DA_IA_ATINGIDO_TENTE_NOVAMENTE_EM_1_MINUTO'});const b=await body(req);if(b.mode==='assistant')return send(res,200,{ok:true,result:await aiAssistant(String(b.message||''),b.context||{},b.history||[])});if(b.mode==='insights')return send(res,200,{ok:true,result:await aiInsights(b.context||{})});if(b.mode==='romaneio_texto')return send(res,200,{ok:true,result:await ai(String(b.text||'').slice(0,50000))});if(b.mode==='mini_risco_imagem')return send(res,200,{ok:true,result:await aiMiniRisk(String(b.image||''))});return send(res,400,{ok:false,error:'MODO_DE_IA_NAO_SUPORTADO'})}
if(req.method==='GET'&&p==='/api/oficinas'){const companyId=await requireScope(req,res);if(!companyId)return;const q=await db('SELECT id,name,code,contact_name,phone,address,active,created_at FROM oficinas WHERE company_id=$1 ORDER BY active DESC,name',[companyId]);return send(res,200,{oficinas:q.rows})}
if(req.method==='POST'&&p==='/api/oficinas'){const companyId=await requireScope(req,res);if(!companyId)return;const b=await body(req);const name=String(b.name||'').trim().toUpperCase();if(name.length<2)return send(res,400,{ok:false,error:'NOME_DA_OFICINA_OBRIGATORIO'});const q=await db('INSERT INTO oficinas(company_id,name,code,contact_name,phone,address,active) VALUES($1,$2,$3,$4,$5,$6,TRUE) RETURNING *',[companyId,name,String(b.code||'').trim().toUpperCase(),String(b.contactName||'').trim().toUpperCase(),String(b.phone||'').trim(),String(b.address||'').trim().toUpperCase()]);return send(res,200,{ok:true,oficina:q.rows[0]})}
if(req.method==='PATCH'&&p.startsWith('/api/oficinas/')&&!p.endsWith('/envios')){const companyId=await requireScope(req,res);if(!companyId)return;const id=Number(p.slice('/api/oficinas/'.length));const b=await body(req);const old=await db('SELECT * FROM oficinas WHERE id=$1 AND company_id=$2',[id,companyId]);if(!old.rows.length)return send(res,404,{ok:false,error:'OFICINA_NAO_ENCONTRADA'});const cur=old.rows[0];const q=await db('UPDATE oficinas SET name=$1,code=$2,contact_name=$3,phone=$4,address=$5,active=$6,updated_at=NOW() WHERE id=$7 AND company_id=$8 RETURNING *',[b.name==null?cur.name:String(b.name).trim().toUpperCase(),b.code==null?cur.code:String(b.code).trim().toUpperCase(),b.contactName==null?cur.contact_name:String(b.contactName).trim().toUpperCase(),b.phone==null?cur.phone:String(b.phone).trim(),b.address==null?cur.address:String(b.address).trim().toUpperCase(),b.active==null?cur.active:Boolean(b.active),id,companyId]);return send(res,200,{ok:true,oficina:q.rows[0]})}
if(req.method==='GET'&&p==='/api/aviamentos/envios-oficina'){const companyId=await requireScope(req,res);if(!companyId)return;const q=await db(`SELECT e.id,e.oc,e.notes,e.items,e.created_at,o.name oficina,u.username FROM envios_aviamentos e JOIN oficinas o ON o.id=e.oficina_id LEFT JOIN app_users u ON u.id=e.user_id WHERE e.company_id=$1 ORDER BY e.id DESC LIMIT 500`,[companyId]);return send(res,200,{envios:q.rows})}
if(req.method==='POST'&&p==='/api/aviamentos/envio-oficina'){const companyId=await requireScope(req,res);if(!companyId)return;const user=await currentDbUser(req);const b=await body(req);const oficinaId=Number(b.oficinaId);const oc=String(b.oc||'').trim().toUpperCase();const items=Array.isArray(b.items)?b.items:[];if(!oficinaId||!items.length)return send(res,400,{ok:false,error:'OFICINA_E_ITENS_OBRIGATORIOS'});const client=await pool.connect();try{await client.query('BEGIN');const of=await client.query('SELECT id,name FROM oficinas WHERE id=$1 AND company_id=$2 AND active=TRUE FOR SHARE',[oficinaId,companyId]);if(!of.rows.length){await client.query('ROLLBACK');return send(res,404,{ok:false,error:'OFICINA_NAO_ENCONTRADA'})}const saved=[];for(const item of items){const id=String(item.id||'');const qty=Number(item.quantity);if(!id||!Number.isFinite(qty)||qty<=0)throw Object.assign(Error('ITEM_DE_ENVIO_INVALIDO'),{statusCode:400});const r=await client.query('SELECT id,payload,version FROM aviamentos WHERE id=$1 AND company_id=$2 FOR UPDATE',[id,companyId]);if(!r.rows.length)throw Object.assign(Error('AVIAMENTO_NAO_ENCONTRADO'),{statusCode:404});const row=r.rows[0],payload=row.payload;const decimals=String(payload.unit||'').toUpperCase()==='M'?2:0;const current=Number(payload.stock)||0;const next=Number((current-qty).toFixed(decimals));if(next<0)throw Object.assign(Error(`ESTOQUE_INSUFICIENTE:${payload.name}:${current}`),{statusCode:409});payload.stock=next;await client.query('UPDATE aviamentos SET payload=$1,updated_at=NOW(),version=version+1 WHERE id=$2 AND company_id=$3',[payload,id,companyId]);saved.push({id,name:payload.name,unit:payload.unit,quantity:qty,stockAfter:next})}const ins=await client.query('INSERT INTO envios_aviamentos(company_id,oficina_id,user_id,oc,notes,items) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,created_at',[companyId,oficinaId,user?.id||null,oc,String(b.notes||'').trim().toUpperCase(),JSON.stringify(saved)]);await client.query('COMMIT');return send(res,200,{ok:true,envio:{id:String(ins.rows[0].id),created_at:ins.rows[0].created_at,oficina:of.rows[0].name,oc,items:saved}})}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}
if(req.method==='GET'&&p==='/api/aviamentos'){const companyId=await requireScope(req,res);if(!companyId)return;if(!pool)return send(res,200,{aviamentos:[]});const q=await db('SELECT id,payload FROM aviamentos WHERE company_id=$1 ORDER BY id',[companyId]);return send(res,200,{aviamentos:q.rows.map(x=>({...x.payload,id:String(x.id)}))})}
if(req.method==='POST'&&p==='/api/aviamentos/sync'){const companyId=await requireScope(req,res);if(!companyId)return;const b=await body(req);if(!Array.isArray(b.aviamentos))return send(res,400,{ok:false,error:'AVIAMENTOS_INVALIDOS'});if(!pool)return send(res,200,{ok:true,localOnly:true});const client=await pool.connect();try{await client.query('BEGIN');for(const x of b.aviamentos){const id=String(x.id||'').trim();if(!id)continue;const payload={id,group:String(x.group||'').trim().toUpperCase(),name:String(x.name||'').trim().toUpperCase(),unit:String(x.unit||'UN').trim().toUpperCase(),stock:Number(x.stock)||0,min:Number(x.min)||0,rollMeters:Number(x.rollMeters)||0,rollsPerBox:Number(x.rollsPerBox)||0};if(payload.stock<0||payload.min<0)throw Object.assign(Error('ESTOQUE_INVALIDO'),{statusCode:400});await client.query(`INSERT INTO aviamentos(id,payload,company_id) VALUES($1,$2,$3) ON CONFLICT(company_id,id) DO UPDATE SET payload=EXCLUDED.payload,updated_at=NOW(),version=aviamentos.version+1`,[id,payload,companyId])}await client.query('COMMIT');return send(res,200,{ok:true})}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}
if(req.method==='POST'&&p.startsWith('/api/aviamentos/')&&p.endsWith('/movimento')){const companyId=await requireScope(req,res);if(!companyId)return;const id=decodeURIComponent(p.slice('/api/aviamentos/'.length,-'/movimento'.length));const b=await body(req);const q=Number(b.quantity);const dir=Number(b.direction);if(!id||!Number.isFinite(q)||q<=0||![1,-1].includes(dir))return send(res,400,{ok:false,error:'MOVIMENTO_INVALIDO'});if(!pool)return send(res,200,{ok:true,localOnly:true,id,quantity:q,direction:dir});const client=await pool.connect();try{await client.query('BEGIN');const r=await client.query('SELECT id,payload,version FROM aviamentos WHERE id=$1 AND company_id=$2 FOR UPDATE',[id,companyId]);if(!r.rows.length){await client.query('ROLLBACK');return send(res,404,{ok:false,error:'AVIAMENTO_NAO_ENCONTRADO'})}const row=r.rows[0],payload=row.payload;const decimals=String(payload.unit||'').toUpperCase()==='M'?2:0;const current=Number(payload.stock)||0;const next=Number((current+dir*q).toFixed(decimals));if(next<0){await client.query('ROLLBACK');return send(res,409,{ok:false,error:'ESTOQUE_INSUFICIENTE',stock:current})}payload.stock=next;const u=await client.query(`UPDATE aviamentos SET payload=$1,updated_at=NOW(),version=version+1 WHERE id=$2 AND company_id=$3 RETURNING id,payload,version,updated_at`,[payload,id,companyId]);await client.query('COMMIT');return send(res,200,{ok:true,aviamento:{...u.rows[0].payload,id:String(u.rows[0].id),version:Number(u.rows[0].version),updated_at:u.rows[0].updated_at}})}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}
if((req.method==='PATCH'||req.method==='POST')&&p.startsWith('/api/aviamentos/')&&!p.endsWith('/movimento')){const companyId=await requireScope(req,res);if(!companyId)return;const id=decodeURIComponent(p.slice('/api/aviamentos/'.length));const b=await body(req);if(!id)return send(res,400,{ok:false,error:'AVIAMENTO_ID_OBRIGATORIO'});const payload={id,group:String(b.group||'').trim().toUpperCase(),name:String(b.name||'').trim().toUpperCase(),unit:String(b.unit||'UN').trim().toUpperCase(),stock:Number(b.stock)||0,min:Number(b.min)||0,rollMeters:Number(b.rollMeters)||0,rollsPerBox:Number(b.rollsPerBox)||0};if(payload.stock<0||payload.min<0)return send(res,400,{ok:false,error:'ESTOQUE_INVALIDO'});if(!pool)return send(res,200,{ok:true,aviamento:payload,localOnly:true});const expected=b.expectedVersion==null?null:Number(b.expectedVersion);const q=expected==null?await db(`INSERT INTO aviamentos(id,payload,company_id) VALUES($1,$2,$3) ON CONFLICT(company_id,id) DO UPDATE SET payload=EXCLUDED.payload,updated_at=NOW(),version=aviamentos.version+1 RETURNING id,payload,version,updated_at`,[id,payload,companyId]):await db(`INSERT INTO aviamentos(id,payload,company_id) VALUES($1,$2,$3) ON CONFLICT(company_id,id) DO UPDATE SET payload=EXCLUDED.payload,updated_at=NOW(),version=aviamentos.version+1 WHERE aviamentos.version=$4 RETURNING id,payload,version,updated_at`,[id,payload,companyId,expected]);if(!q.rows.length)return send(res,409,{ok:false,error:'DADOS_ALTERADOS_POR_OUTRO_DISPOSITIVO'});return send(res,200,{ok:true,aviamento:{...q.rows[0].payload,id:String(q.rows[0].id),version:Number(q.rows[0].version),updated_at:q.rows[0].updated_at}})}
if(req.method==='GET'&&p==='/api/tecidos'){const companyId=await requireScope(req,res);if(!companyId)return;if(!pool)return send(res,200,{fabrics:[]});const q=await db('SELECT id,payload FROM tecidos WHERE company_id=$1 ORDER BY id DESC',[companyId]);return send(res,200,{fabrics:q.rows.map(x=>({...x.payload,id:String(x.id)}))})}
if(req.method==='POST'&&p==='/api/tecidos'){const companyId=await requireScope(req,res);if(!companyId)return;const b=await body(req);if(!b.fabric||!Array.isArray(b.rolls)||!b.rolls.length)return send(res,400,{ok:false,error:'TECIDO_E_ROLOS_OBRIGATORIOS'});const payload={fabric:String(b.fabric).trim().toUpperCase(),nf:String(b.nf||'').trim().toUpperCase(),date:b.date||new Date().toISOString().slice(0,10),ref:String(b.ref||'').trim().toUpperCase(),rolls:b.rolls.map(r=>({id:String(r.id||Date.now()+Math.random()),nuance:String(r.nuance||'').trim().toUpperCase(),lot:String(r.lot||'').trim().toUpperCase(),meters:Number(r.meters),code:String(r.code||'').trim().toUpperCase()}))};if(!pool)return send(res,200,{fabric:{...payload,id:String(Date.now())}});const q=await db('INSERT INTO tecidos(payload,company_id) VALUES($1,$2) RETURNING id,payload',[payload,companyId]);return send(res,200,{fabric:{...q.rows[0].payload,id:String(q.rows[0].id)}})}
if(req.method==='POST'&&p==='/api/tecidos/saida'){const companyId=await requireScope(req,res);if(!companyId)return;const b=await body(req);const m=Number(b.meters),pieces=Number(b.pieces),oc=String(b.oc||'').trim().toUpperCase();if(!String(b.rollId||''))return send(res,400,{ok:false,error:'ROLO_NAO_ENCONTRADO'});if(!Number.isFinite(m)||m<=0)return send(res,400,{ok:false,error:'METRAGEM_INVALIDA'});if(!Number.isInteger(pieces)||pieces<=0)return send(res,400,{ok:false,error:'PECAS_INVALIDAS'});if(!oc)return send(res,400,{ok:false,error:'OC_OBRIGATORIA'});if(!pool)return send(res,200,{localOnly:true,rollId:String(b.rollId),meters:m,pieces,oc,note:String(b.note||'').trim().toUpperCase()});const client=await pool.connect();try{await client.query('BEGIN');const all=await client.query('SELECT id,payload,version FROM tecidos WHERE company_id=$1 FOR UPDATE',[companyId]);let owner=null;for(const row of all.rows){if((row.payload.rolls||[]).some(r=>String(r.id)===String(b.rollId))){owner=row;break}}if(!owner){await client.query('ROLLBACK');return send(res,404,{ok:false,error:'ROLO_NAO_ENCONTRADO'})}const roll=owner.payload.rolls.find(r=>String(r.id)===String(b.rollId));if(m>Number(roll.meters)+1e-9){await client.query('ROLLBACK');return send(res,409,{ok:false,error:'METRAGEM_MAIOR_QUE_DISPONIVEL',disponivel:Number(roll.meters)})}roll.meters=Number((Number(roll.meters)-m).toFixed(3));const payload={type:'SAÍDA',date:new Date().toISOString().slice(0,10),fabric:owner.payload.fabric,nuance:roll.nuance||'',meters:m,pieces,oc,note:String(b.note||'').trim().toUpperCase(),rollId:String(b.rollId)};const nq=await client.query('UPDATE tecidos SET payload=$1,updated_at=NOW(),version=version+1 WHERE id=$2 AND company_id=$3 RETURNING id,payload,version',[owner.payload,String(owner.id),companyId]);const mv=await client.query('INSERT INTO movimentos_tecido(payload,company_id) VALUES($1,$2) RETURNING id,created_at',[payload,companyId]);await client.query('COMMIT');return send(res,200,{fabric:{...nq.rows[0].payload,id:String(nq.rows[0].id),version:Number(nq.rows[0].version)},movement:{id:String(mv.rows[0].id),created_at:mv.rows[0].created_at}})}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}
if(req.method==='GET'&&p==='/api/movimentos'){const companyId=await requireScope(req,res);if(!companyId)return;if(!pool)return send(res,200,{history:[]});const q=await db('SELECT id,payload,created_at FROM movimentos_tecido WHERE company_id=$1 ORDER BY id DESC LIMIT 500',[companyId]);return send(res,200,{history:q.rows.map(x=>({...x.payload,id:String(x.id),created_at:x.created_at}))})}
if(req.method==='POST'&&p==='/api/romaneios/draft'){const companyId=await requireScope(req,res);if(!companyId)return;const b=await body(req);if(!pool)return send(res,200,{ok:true,localOnly:true});const key=String(b.draftKey||'tecnoflow');const payload=b.payload||{};const q=await db(`INSERT INTO romaneios(company_id,draft_key,payload,status) VALUES($1,$2,$3,'RASCUNHO') ON CONFLICT(company_id,draft_key) WHERE status='RASCUNHO' DO UPDATE SET payload=EXCLUDED.payload,updated_at=NOW() RETURNING id,payload,status,updated_at`,[companyId,key,payload]);return send(res,200,{ok:true,romaneio:{...q.rows[0],id:String(q.rows[0].id)}})}
if(req.method==='POST'&&p==='/api/romaneios'){const companyId=await requireScope(req,res);if(!companyId)return;const b=await body(req);const payload=b.payload||{};if(!payload.text)return send(res,400,{ok:false,error:'ROMANEIO_VAZIO'});if(!pool)return send(res,200,{ok:true,romaneio:{id:String(Date.now()),payload,status:'SALVO',created_at:new Date().toISOString()}});const key=String(b.draftKey||'');const q=key?await db(`UPDATE romaneios SET payload=$1,status='SALVO',updated_at=NOW() WHERE company_id=$2 AND draft_key=$3 AND status='RASCUNHO' RETURNING id,payload,status,created_at`,[payload,companyId,key]):{rows:[]};if(q.rows.length)return send(res,200,{ok:true,romaneio:{...q.rows[0],id:String(q.rows[0].id)}});const n=await db(`INSERT INTO romaneios(company_id,payload,status) VALUES($1,$2,'SALVO') RETURNING id,payload,status,created_at`,[companyId,payload]);return send(res,200,{ok:true,romaneio:{...n.rows[0],id:String(n.rows[0].id)}})}
if(req.method==='GET'&&p==='/api/romaneios'){const companyId=await requireScope(req,res);if(!companyId)return;if(!pool)return send(res,200,{romaneios:[]});const q=await db(`SELECT id,payload,status,created_at FROM romaneios WHERE company_id=$1 AND status='SALVO' ORDER BY id DESC LIMIT 200`,[companyId]);return send(res,200,{romaneios:q.rows.map(x=>({...x,id:String(x.id)}))})}
if(req.method==='GET'){const rel=path.normalize(p==='/'?'/index.html':p).replace(/^[/\\]+/,'');const roots=[path.resolve(ROOT,'public'),ROOT];for(const base of roots){const file=path.resolve(base,rel);if(file!==base&&!file.startsWith(base+path.sep))continue;if(fs.existsSync(file)&&fs.statSync(file).isFile()){const ext=path.extname(file).toLowerCase();if(file===path.resolve(ROOT,'server.js')||file===path.resolve(ROOT,'package.json'))continue;return send(res,200,fs.readFileSync(file),MIME[ext]||'application/octet-stream')}}}
return send(res,404,{ok:false,error:'NOT_FOUND'})}
const server=http.createServer((req,res)=>routes(req,res).catch(e=>{const code=Number(e.statusCode)||500;if(code>=500)console.error(e);send(res,code,{ok:false,error:e.message||'ERRO_INTERNO'})}));
init().then(()=>server.listen(PORT,HOST,()=>{console.log(`ESTOQUE DE TECIDO PLUS+ ${APP_VERSION} ON ${PORT}`);console.log(`Login pelo banco: ${Boolean(pool)}`)})).catch(e=>{console.error('DB INIT',e);server.listen(PORT,HOST,()=>console.log(`ESTOQUE DE TECIDO PLUS+ ${APP_VERSION} ON ${PORT} SEM DB`))});
process.on('SIGTERM',async()=>{server.close();if(pool)await pool.end();process.exit(0)});
