const http=require('http');const fs=require('fs');const path=require('path');
let Pool=null;
try{Pool=require('pg').Pool}catch{Pool=null}
const PORT=Number(process.env.PORT)||3000;const HOST='0.0.0.0';const ROOT=__dirname;const OPENAI_API_KEY=process.env.OPENAI_API_KEY||'';const OPENAI_MODEL=process.env.OPENAI_MODEL||'gpt-5.6-sol';
const APP_VERSION='V31 PRODUÇÃO';
const AI_RATE_LIMIT=20;const AI_RATE_WINDOW_MS=60_000;const aiRate=new Map();
const pool=(Pool&&process.env.DATABASE_URL)?new Pool({connectionString:process.env.DATABASE_URL,ssl:{rejectUnauthorized:false},max:5,idleTimeoutMillis:30000}):null;
const MIME={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.svg':'image/svg+xml','.ico':'image/x-icon'};
function send(res,code,data,type='application/json; charset=utf-8'){if(res.headersSent)return;res.writeHead(code,{'Content-Type':type,'Cache-Control':'no-store'});res.end(Buffer.isBuffer(data)?data:typeof data==='string'?data:JSON.stringify(data))}
function body(req){return new Promise((resolve,reject)=>{let s='',tooLarge=false;req.on('data',c=>{if(tooLarge)return;s+=c;if(s.length>15*1024*1024){tooLarge=true;reject(Object.assign(Error('PAYLOAD_TOO_LARGE'),{statusCode:413}));req.resume()}});req.on('end',()=>{if(tooLarge)return;if(!s)return resolve({});try{resolve(JSON.parse(s))}catch{reject(Object.assign(Error('JSON_INVALIDO'),{statusCode:400}))}});req.on('error',reject)})}
async function db(sql,params=[]){if(!pool)throw Error('DATABASE_NAO_CONFIGURADO');return pool.query(sql,params)}
async function init(){if(!pool)return;await db(`CREATE TABLE IF NOT EXISTS tecidos(id BIGSERIAL PRIMARY KEY,payload JSONB NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE TABLE IF NOT EXISTS movimentos_tecido(id BIGSERIAL PRIMARY KEY,payload JSONB NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE TABLE IF NOT EXISTS romaneios(id BIGSERIAL PRIMARY KEY,draft_key TEXT,payload JSONB NOT NULL,status TEXT NOT NULL DEFAULT 'SALVO',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE UNIQUE INDEX IF NOT EXISTS romaneios_draft_key_idx ON romaneios(draft_key) WHERE status='RASCUNHO';CREATE TABLE IF NOT EXISTS aviamentos(id TEXT PRIMARY KEY,payload JSONB NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE INDEX IF NOT EXISTS movimentos_tecido_created_idx ON movimentos_tecido(created_at DESC);CREATE INDEX IF NOT EXISTS tecidos_updated_idx ON tecidos(updated_at DESC);`);await db(`ALTER TABLE tecidos ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 1;ALTER TABLE aviamentos ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 1;`)}
function jsonExtract(r){if(typeof r?.output_text==='string')return r.output_text;return (r?.output||[]).flatMap(i=>(i?.content||[]).map(c=>c?.text||'')).join('\n')}
function parseJson(s){try{return JSON.parse(s)}catch{}const m=String(s||'').match(/\{[\s\S]*\}/);if(m)try{return JSON.parse(m[0])}catch{}return null}
async function ai(text){if(!OPENAI_API_KEY)throw Error('OPENAI_API_KEY_NAO_CONFIGURADA');const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),90000);try{const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${OPENAI_API_KEY}`},signal:controller.signal,body:JSON.stringify({model:OPENAI_MODEL,instructions:`VOCÊ É O LEITOR DE ROMANEIOS DE TECIDO DO ESTOQUE PLUS. RETORNE SOMENTE JSON VÁLIDO. NÃO INVENTE DADOS. DIFERENCIE ROMANEIO, NF, PEDIDO, TECIDO, ARTIGO, NUANCE, REFERÊNCIA, METROS, PEÇAS E PESOS. REGISTRE DIVERGÊNCIAS. CONFIANÇA DE 0 A 100. FORMATO: {\"documento\":{\"romaneio\":\"\",\"notaFiscal\":\"\",\"pedido\":\"\",\"data\":\"\"},\"produto\":{\"tecido\":\"\",\"artigo\":\"\",\"nuance\":\"\",\"referencia\":\"\"},\"totais\":{\"pecas\":null,\"metros\":null,\"pesoLiquido\":null,\"pesoBruto\":null},\"conferencia\":{\"divergencias\":[],\"observacoes\":[],\"confianca\":0}}`,input:text})});const t=await r.text();if(!r.ok)throw Error(`OPENAI_${r.status}: ${t.slice(0,700)}`);return parseJson(jsonExtract(JSON.parse(t)))||{conferencia:{confianca:0,divergencias:['A IA NÃO RETORNOU JSON VÁLIDO.'],observacoes:[jsonExtract(JSON.parse(t)).slice(0,1500)]}}}finally{clearTimeout(timer)}}
async function callOpenAI(instructions,input,timeout=90000){if(!OPENAI_API_KEY)throw Error('OPENAI_API_KEY_NAO_CONFIGURADA');const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeout);try{const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${OPENAI_API_KEY}`},signal:controller.signal,body:JSON.stringify({model:OPENAI_MODEL,instructions,input})});const t=await r.text();if(!r.ok)throw Error(`OPENAI_${r.status}: ${t.slice(0,700)}`);return JSON.parse(t)}finally{clearTimeout(timer)}}
function safeContext(context){const c=context&&typeof context==='object'?context:{};return JSON.stringify(c).slice(0,70000)}
async function aiAssistant(message,context={},history=[]){const system=`VOCÊ É A IA CENTRAL DO ESTOQUE DE TECIDO PLUS+, UM ASSISTENTE OPERACIONAL DE ALTO NÍVEL.
MISSÃO: ajudar a controlar tecidos e aviamentos, conferir cortes e romaneios, fazer cálculos exatos, detectar inconsistências, explicar causas e montar planos de ação.
CAPACIDADES: análise de estoque, cálculo de necessidade, conferência OC/grade/pares, análise de rolos/nuances, leitura e auditoria de romaneios, comparação de dados, detecção de divergências, planejamento de reposição e perguntas de esclarecimento.
REGRAS DE CONFIABILIDADE: NUNCA INVENTE estoque, histórico, medidas ou movimentações. Diferencie claramente DADO INFORMADO, CÁLCULO, INFERÊNCIA e ALERTA. Se faltar dado, peça somente o dado necessário. Refaça contas antes de responder.
REGRAS DE AVIAMENTOS: CÓS 1,3 M/PEÇA, ROLO 50 M; REFLETIVO 1,0 M/PEÇA, ROLO 50 M, 20 ROLOS/CAIXA; ELÁSTICO 0,8 M/PEÇA, ROLO 25 M; ZÍPER 1/PEÇA, pacote padrão 100; ETIQUETA TAMANHO 0,35 G/PEÇA; ETIQUETA COMPOSIÇÃO 0,4 G/PEÇA. GRADE PADRÃO: 38,40,42,44,46,48.
ESTOQUE: quando houver estoque disponível no contexto, compare necessidade com estoque e mostre saldo projetado. Não baixe estoque nem altere dados sem uma ação explícita do usuário.
FORMATO: português do Brasil, direto, organizado, números em padrão brasileiro. Para problemas, use: RESUMO / DADOS / CÁLCULO / ALERTAS / PRÓXIMA AÇÃO.
CONTEXTO ATUAL: ${safeContext(context)}
HISTÓRICO RECENTE DA CONVERSA: ${JSON.stringify(Array.isArray(history)?history.slice(-12):[]).slice(0,20000)}`;const r=await callOpenAI(system,String(message||'').slice(0,20000));const out=jsonExtract(r);return {answer:out||'NÃO FOI POSSÍVEL GERAR UMA RESPOSTA.'}}
async function aiInsights(context={}){const system=`VOCÊ É O AUDITOR INTELIGENTE DO ESTOQUE DE TECIDO PLUS+.
Analise os dados fornecidos e produza uma auditoria operacional. Não invente nada. Só trate como alerta aquilo que puder ser sustentado pelos dados. Para estoque de aviamentos, compare estoque atual com necessidades calculadas quando existirem. Para tecidos, procure rolos com metragem inválida, dados incompletos, possíveis duplicidades e concentrações por nuance. Para romaneios, procure campos vazios, valores incompatíveis e divergências já registradas.
RETORNE SOMENTE JSON válido no formato: {"resumo":"","nivel":"NORMAL|ATENCAO|CRITICO","alertas":[{"item":"","tipo":"","detalhe":""}],"prioridades":[""],"recomendacoes":[""],"dados_faltantes":[""],"confianca":0}. Não faça baixa nem alteração de estoque. CONTEXTO: ${safeContext(context)}`;const r=await callOpenAI(system,'FAÇA A AUDITORIA COMPLETA DOS DADOS ATUAIS.');return parseJson(jsonExtract(r))||{resumo:'A IA não retornou JSON válido.',nivel:'ATENCAO',alertas:[],prioridades:[],recomendacoes:[],dados_faltantes:[],confianca:0}}
async function aiMiniRisk(imageData){if(!OPENAI_API_KEY)throw Error('OPENAI_API_KEY_NAO_CONFIGURADA');if(!/^data:image\/(png|jpe?g|webp);base64,/i.test(imageData))throw Error('IMAGEM_INVALIDA');const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),90000);try{const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${OPENAI_API_KEY}`},signal:controller.signal,body:JSON.stringify({model:OPENAI_MODEL,instructions:`LEIA A FOTO DE UM MINI RISCO DE CONFECÇÃO. RETORNE SOMENTE JSON VÁLIDO E NÃO INVENTE NÚMEROS. IDENTIFIQUE OC/TOTAL DE PEÇAS, GRADE POR TAMANHO E PARES. A GRADE É A SOMA DOS VALORES DOS TAMANHOS. SE A FOTO MOSTRAR UMA EXPRESSÃO COMO 16 X 130 = 2080, USE 16 COMO GRADE, 130 COMO PARES E 2080 COMO OC. TENTE OS TAMANHOS 36,38,40,42,44,46,48,50,52,54. FORMATO: {\"oc\":null,\"gradeTotal\":null,\"pares\":null,\"tamanhos\":{\"36\":0,\"38\":0,\"40\":0,\"42\":0,\"44\":0,\"46\":0,\"48\":0,\"50\":0,\"52\":0,\"54\":0},\"confianca\":0,\"observacoes\":[]}`,input:[{role:'user',content:[{type:'input_text',text:'LEIA ESTA FOTO DO MINI RISCO E EXTRAIA OS DADOS.'},{type:'input_image',image_url:imageData}]}]})});const t=await r.text();if(!r.ok)throw Error(`OPENAI_${r.status}: ${t.slice(0,700)}`);return parseJson(jsonExtract(JSON.parse(t)))||{confianca:0,observacoes:['A IA NÃO RETORNOU JSON VÁLIDO.']}}finally{clearTimeout(timer)}}
function allowAI(req){const now=Date.now();const ip=String(req.headers['x-forwarded-for']||req.socket.remoteAddress||'unknown').split(',')[0].trim();const hit=aiRate.get(ip)||{at:now,count:0};if(now-hit.at>=AI_RATE_WINDOW_MS){hit.at=now;hit.count=0}hit.count++;aiRate.set(ip,hit);if(aiRate.size>5000){for(const [k,v] of aiRate)if(now-v.at>AI_RATE_WINDOW_MS)aiRate.delete(k)}return hit.count<=AI_RATE_LIMIT}
async function routes(req,res){const p=decodeURIComponent((req.url||'/').split('?')[0]);if(req.method==='GET'&&p==='/api/health'){let dbOk=false,dbLatency=null;if(pool){const t=Date.now();try{await db('SELECT 1');dbOk=true;dbLatency=Date.now()-t}catch{}}return send(res,200,{ok:true,service:`ESTOQUE DE TECIDO PLUS+ ${APP_VERSION}`,version:APP_VERSION,database:dbOk,aiConfigured:Boolean(OPENAI_API_KEY),model:OPENAI_MODEL,dbLatencyMs:dbLatency,serverTime:new Date().toISOString()})}
if(req.method==='POST'&&p==='/api/ai'){if(!OPENAI_API_KEY)return send(res,503,{ok:false,error:'OPENAI_API_KEY_NAO_CONFIGURADA'});if(!allowAI(req))return send(res,429,{ok:false,error:'LIMITE_DA_IA_ATINGIDO_TENTE_NOVAMENTE_EM_1_MINUTO'});const b=await body(req);if(b.mode==='assistant')return send(res,200,{ok:true,result:await aiAssistant(String(b.message||''),b.context||{},b.history||[])});if(b.mode==='insights')return send(res,200,{ok:true,result:await aiInsights(b.context||{})});if(b.mode==='romaneio_texto')return send(res,200,{ok:true,result:await ai(String(b.text||'').slice(0,50000))});if(b.mode==='mini_risco_imagem')return send(res,200,{ok:true,result:await aiMiniRisk(String(b.image||''))});return send(res,400,{ok:false,error:'MODO_DE_IA_NAO_SUPORTADO'})}
if(req.method==='GET'&&p==='/api/aviamentos'){if(!pool)return send(res,200,{aviamentos:[]});const q=await db('SELECT id,payload FROM aviamentos ORDER BY id');return send(res,200,{aviamentos:q.rows.map(x=>({...x.payload,id:String(x.id)}))})}
if(req.method==='POST'&&p==='/api/aviamentos/sync'){const b=await body(req);if(!Array.isArray(b.aviamentos))return send(res,400,{ok:false,error:'AVIAMENTOS_INVALIDOS'});if(!pool)return send(res,200,{ok:true,localOnly:true});const client=await pool.connect();try{await client.query('BEGIN');for(const x of b.aviamentos){const id=String(x.id||'').trim();if(!id)continue;const payload={id,group:String(x.group||'').trim().toUpperCase(),name:String(x.name||'').trim().toUpperCase(),unit:String(x.unit||'UN').trim().toUpperCase(),stock:Number(x.stock)||0,min:Number(x.min)||0,rollMeters:Number(x.rollMeters)||0,rollsPerBox:Number(x.rollsPerBox)||0};if(payload.stock<0||payload.min<0)throw Object.assign(Error('ESTOQUE_INVALIDO'),{statusCode:400});await client.query(`INSERT INTO aviamentos(id,payload) VALUES($1,$2) ON CONFLICT(id) DO UPDATE SET payload=EXCLUDED.payload,updated_at=NOW(),version=aviamentos.version+1`,[id,payload])}await client.query('COMMIT');return send(res,200,{ok:true})}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}
if(req.method==='POST'&&p.startsWith('/api/aviamentos/')&&p.endsWith('/movimento')){const id=decodeURIComponent(p.slice('/api/aviamentos/'.length,-'/movimento'.length));const b=await body(req);const q=Number(b.quantity);const dir=Number(b.direction);if(!id||!Number.isFinite(q)||q<=0||![1,-1].includes(dir))return send(res,400,{ok:false,error:'MOVIMENTO_INVALIDO'});if(!pool)return send(res,200,{ok:true,localOnly:true,id,quantity:q,direction:dir});const client=await pool.connect();try{await client.query('BEGIN');const r=await client.query('SELECT id,payload,version FROM aviamentos WHERE id=$1 FOR UPDATE',[id]);if(!r.rows.length){await client.query('ROLLBACK');return send(res,404,{ok:false,error:'AVIAMENTO_NAO_ENCONTRADO'})}const row=r.rows[0],payload=row.payload;const decimals=String(payload.unit||'').toUpperCase()==='M'?2:0;const current=Number(payload.stock)||0;const next=Number((current+dir*q).toFixed(decimals));if(next<0){await client.query('ROLLBACK');return send(res,409,{ok:false,error:'ESTOQUE_INSUFICIENTE',stock:current})}payload.stock=next;const u=await client.query(`UPDATE aviamentos SET payload=$1,updated_at=NOW(),version=version+1 WHERE id=$2 RETURNING id,payload,version,updated_at`,[payload,id]);await client.query('COMMIT');return send(res,200,{ok:true,aviamento:{...u.rows[0].payload,id:String(u.rows[0].id),version:Number(u.rows[0].version),updated_at:u.rows[0].updated_at}})}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}
if((req.method==='PATCH'||req.method==='POST')&&p.startsWith('/api/aviamentos/')&&!p.endsWith('/movimento')){const id=decodeURIComponent(p.slice('/api/aviamentos/'.length));const b=await body(req);if(!id)return send(res,400,{ok:false,error:'AVIAMENTO_ID_OBRIGATORIO'});const payload={id,group:String(b.group||'').trim().toUpperCase(),name:String(b.name||'').trim().toUpperCase(),unit:String(b.unit||'UN').trim().toUpperCase(),stock:Number(b.stock)||0,min:Number(b.min)||0,rollMeters:Number(b.rollMeters)||0,rollsPerBox:Number(b.rollsPerBox)||0};if(payload.stock<0||payload.min<0)return send(res,400,{ok:false,error:'ESTOQUE_INVALIDO'});if(!pool)return send(res,200,{ok:true,aviamento:payload,localOnly:true});const expected=b.expectedVersion==null?null:Number(b.expectedVersion);const q=expected==null?await db(`INSERT INTO aviamentos(id,payload) VALUES($1,$2) ON CONFLICT(id) DO UPDATE SET payload=EXCLUDED.payload,updated_at=NOW(),version=aviamentos.version+1 RETURNING id,payload,version,updated_at`,[id,payload]):await db(`INSERT INTO aviamentos(id,payload) VALUES($1,$2) ON CONFLICT(id) DO UPDATE SET payload=EXCLUDED.payload,updated_at=NOW(),version=aviamentos.version+1 WHERE aviamentos.version=$3 RETURNING id,payload,version,updated_at`,[id,payload,expected]);if(!q.rows.length)return send(res,409,{ok:false,error:'DADOS_ALTERADOS_POR_OUTRO_DISPOSITIVO'});return send(res,200,{ok:true,aviamento:{...q.rows[0].payload,id:String(q.rows[0].id),version:Number(q.rows[0].version),updated_at:q.rows[0].updated_at}})}
if(req.method==='GET'&&p==='/api/tecidos'){if(!pool)return send(res,200,{fabrics:[]});const q=await db('SELECT id,payload FROM tecidos ORDER BY id DESC');return send(res,200,{fabrics:q.rows.map(x=>({...x.payload,id:String(x.id)}))})}
if(req.method==='POST'&&p==='/api/tecidos'){const b=await body(req);if(!b.fabric||!Array.isArray(b.rolls)||!b.rolls.length)return send(res,400,{ok:false,error:'TECIDO_E_ROLOS_OBRIGATORIOS'});const payload={fabric:String(b.fabric).trim().toUpperCase(),nf:String(b.nf||'').trim().toUpperCase(),date:b.date||new Date().toISOString().slice(0,10),ref:String(b.ref||'').trim().toUpperCase(),rolls:b.rolls.map(r=>({id:String(r.id||Date.now()+Math.random()),nuance:String(r.nuance||'').trim().toUpperCase(),lot:String(r.lot||'').trim().toUpperCase(),meters:Number(r.meters),code:String(r.code||'').trim().toUpperCase()}))};if(!pool)return send(res,200,{fabric:{...payload,id:String(Date.now())}});const q=await db('INSERT INTO tecidos(payload) VALUES($1) RETURNING id,payload',[payload]);return send(res,200,{fabric:{...q.rows[0].payload,id:String(q.rows[0].id)}})}
if(req.method==='POST'&&p==='/api/tecidos/saida'){const b=await body(req);const m=Number(b.meters),pieces=Number(b.pieces),oc=String(b.oc||'').trim().toUpperCase();if(!String(b.rollId||''))return send(res,400,{ok:false,error:'ROLO_NAO_ENCONTRADO'});if(!Number.isFinite(m)||m<=0)return send(res,400,{ok:false,error:'METRAGEM_INVALIDA'});if(!Number.isInteger(pieces)||pieces<=0)return send(res,400,{ok:false,error:'PECAS_INVALIDAS'});if(!oc)return send(res,400,{ok:false,error:'OC_OBRIGATORIA'});if(!pool)return send(res,200,{localOnly:true,rollId:String(b.rollId),meters:m,pieces,oc,note:String(b.note||'').trim().toUpperCase()});const client=await pool.connect();try{await client.query('BEGIN');const all=await client.query('SELECT id,payload,version FROM tecidos FOR UPDATE');let owner=null;for(const row of all.rows){if((row.payload.rolls||[]).some(r=>String(r.id)===String(b.rollId))){owner=row;break}}if(!owner){await client.query('ROLLBACK');return send(res,404,{ok:false,error:'ROLO_NAO_ENCONTRADO'})}const roll=owner.payload.rolls.find(r=>String(r.id)===String(b.rollId));if(m>Number(roll.meters)+1e-9){await client.query('ROLLBACK');return send(res,409,{ok:false,error:'METRAGEM_MAIOR_QUE_DISPONIVEL',disponivel:Number(roll.meters)})}roll.meters=Number((Number(roll.meters)-m).toFixed(3));const payload={type:'SAÍDA',date:new Date().toISOString().slice(0,10),fabric:owner.payload.fabric,nuance:roll.nuance||'',meters:m,pieces,oc,note:String(b.note||'').trim().toUpperCase(),rollId:String(b.rollId)};const nq=await client.query('UPDATE tecidos SET payload=$1,updated_at=NOW(),version=version+1 WHERE id=$2 RETURNING id,payload,version',[owner.payload,String(owner.id)]);const mv=await client.query('INSERT INTO movimentos_tecido(payload) VALUES($1) RETURNING id,created_at',[payload]);await client.query('COMMIT');return send(res,200,{fabric:{...nq.rows[0].payload,id:String(nq.rows[0].id),version:Number(nq.rows[0].version)},movement:{id:String(mv.rows[0].id),created_at:mv.rows[0].created_at}})}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}
if(req.method==='GET'&&p==='/api/movimentos'){if(!pool)return send(res,200,{history:[]});const q=await db('SELECT id,payload,created_at FROM movimentos_tecido ORDER BY id DESC LIMIT 500');return send(res,200,{history:q.rows.map(x=>({...x.payload,id:String(x.id),created_at:x.created_at}))})}
if(req.method==='POST'&&p==='/api/romaneios/draft'){const b=await body(req);if(!pool)return send(res,200,{ok:true,localOnly:true});const key=String(b.draftKey||'tecnoflow');const payload=b.payload||{};const q=await db(`INSERT INTO romaneios(draft_key,payload,status) VALUES($1,$2,'RASCUNHO') ON CONFLICT(draft_key) WHERE status='RASCUNHO' DO UPDATE SET payload=EXCLUDED.payload,updated_at=NOW() RETURNING id,payload,status,updated_at`,[key,payload]);return send(res,200,{ok:true,romaneio:{...q.rows[0],id:String(q.rows[0].id)}})}
if(req.method==='POST'&&p==='/api/romaneios'){const b=await body(req);const payload=b.payload||{};if(!payload.text)return send(res,400,{ok:false,error:'ROMANEIO_VAZIO'});if(!pool)return send(res,200,{ok:true,romaneio:{id:String(Date.now()),payload,status:'SALVO',created_at:new Date().toISOString()}});const key=String(b.draftKey||'');const q=key?await db(`UPDATE romaneios SET payload=$1,status='SALVO',updated_at=NOW() WHERE draft_key=$2 AND status='RASCUNHO' RETURNING id,payload,status,created_at`,[payload,key]):{rows:[]};if(q.rows.length)return send(res,200,{ok:true,romaneio:{...q.rows[0],id:String(q.rows[0].id)}});const n=await db(`INSERT INTO romaneios(payload,status) VALUES($1,'SALVO') RETURNING id,payload,status,created_at`,[payload]);return send(res,200,{ok:true,romaneio:{...n.rows[0],id:String(n.rows[0].id)}})}
if(req.method==='GET'&&p==='/api/romaneios'){if(!pool)return send(res,200,{romaneios:[]});const q=await db(`SELECT id,payload,status,created_at FROM romaneios WHERE status='SALVO' ORDER BY id DESC LIMIT 200`);return send(res,200,{romaneios:q.rows.map(x=>({...x,id:String(x.id)}))})}
if(req.method==='GET'){const rel=path.normalize(p==='/'?'/index.html':p).replace(/^[/\\]+/,'');const roots=[path.resolve(ROOT,'public'),ROOT];for(const base of roots){const file=path.resolve(base,rel);if(file!==base&&!file.startsWith(base+path.sep))continue;if(fs.existsSync(file)&&fs.statSync(file).isFile()){const ext=path.extname(file).toLowerCase();if(file===path.resolve(ROOT,'server.js')||file===path.resolve(ROOT,'package.json'))continue;return send(res,200,fs.readFileSync(file),MIME[ext]||'application/octet-stream')}}}
return send(res,404,{ok:false,error:'NOT_FOUND'})}
const server=http.createServer((req,res)=>routes(req,res).catch(e=>{const code=Number(e.statusCode)||500;if(code>=500)console.error(e);send(res,code,{ok:false,error:e.message||'ERRO_INTERNO'})}));
init().then(()=>server.listen(PORT,HOST,()=>console.log(`ESTOQUE DE TECIDO PLUS+ ${APP_VERSION} ON ${PORT}`))).catch(e=>{console.error('DB INIT',e);server.listen(PORT,HOST,()=>console.log(`ESTOQUE DE TECIDO PLUS+ V30 ON ${PORT} SEM DB`))});
process.on('SIGTERM',async()=>{server.close();if(pool)await pool.end();process.exit(0)});
